ALTER TABLE application.request_type DROP COLUMN IF EXISTS display_group_name ;
ALTER TABLE application.request_type ADD COLUMN display_group_name character varying(500); 
COMMENT ON COLUMN application.request_type.display_group_name IS 'SOLA Extension. Used to group request types that have a similar purpose (e.g. Mortgage types or Systematic Registration types). Used by the Add Service dialog to group the request types for display.'; 

UPDATE application.request_type SET display_group_name = 'General Registration' WHERE code = 'regnOnTitle';
UPDATE application.request_type SET display_group_name = 'Supporting' WHERE code = 'serviceEnquiry';
UPDATE application.request_type SET display_group_name = 'Survey' WHERE code = 'surveyPlanCopy';
UPDATE application.request_type SET display_group_name = 'Mortgage' WHERE code = 'varyMortgage';
UPDATE application.request_type SET display_group_name = 'General Registration' WHERE code = 'varyRight';
UPDATE application.request_type SET display_group_name = 'Caveat' WHERE code = 'varyCaveat';
UPDATE application.request_type SET display_group_name = 'Caveat' WHERE code = 'removeCaveat';
UPDATE application.request_type SET display_group_name = 'Caveat' WHERE code = 'caveat';
UPDATE application.request_type SET display_group_name = 'Ownership' WHERE code = 'newOwnership';
UPDATE application.request_type SET display_group_name = 'Survey' WHERE code = 'cadastreChange';
UPDATE application.request_type SET display_group_name = 'Documents' WHERE code = 'documentCopy';
UPDATE application.request_type SET display_group_name = 'Ownership' WHERE code = 'noteOccupation';
UPDATE application.request_type SET display_group_name = 'Supporting' WHERE code = 'cadastreExport';
UPDATE application.request_type SET display_group_name = 'Supporting' WHERE code = 'cadastrePrint';
UPDATE application.request_type SET display_group_name = 'General Registration' WHERE code = 'cancelProperty';
UPDATE application.request_type SET display_group_name = 'General Registration' WHERE code = 'newDigitalTitle';
UPDATE application.request_type SET display_group_name = 'General Registration' WHERE code = 'regnDeeds';
UPDATE application.request_type SET display_group_name = 'Systematic Registration' WHERE code = 'lodgeObjection';
UPDATE application.request_type SET display_group_name = 'General Registration' WHERE code = 'newState';
UPDATE application.request_type SET display_group_name = 'Survey' WHERE code = 'redefineCadastre';
UPDATE application.request_type SET display_group_name = 'Lease' WHERE code = 'registerLease';
UPDATE application.request_type SET display_group_name = 'Mortgage' WHERE code = 'mortgage';
UPDATE application.request_type SET display_group_name = 'Other Registration' WHERE code = 'servitude';
UPDATE application.request_type SET display_group_name = 'Documents' WHERE code = 'regnPowerOfAttorney';
UPDATE application.request_type SET display_group_name = 'Documents' WHERE code = 'regnStandardDocument';
UPDATE application.request_type SET display_group_name = 'General Registration' WHERE code = 'newFreehold';
UPDATE application.request_type SET display_group_name = 'Other Registration' WHERE code = 'limitedRoadAccess';
UPDATE application.request_type SET display_group_name = 'Other Registration' WHERE code = 'waterRights';
UPDATE application.request_type SET display_group_name = 'Other Registration' WHERE code = 'lifeEstate';
UPDATE application.request_type SET display_group_name = 'Other Registration' WHERE code = 'historicOrder';
UPDATE application.request_type SET display_group_name = 'Other Registration' WHERE code = 'usufruct';
UPDATE application.request_type SET display_group_name = 'Documents' WHERE code = 'cnclStandardDocument';
UPDATE application.request_type SET display_group_name = 'Other Registration' WHERE code = 'buildingRestriction';
UPDATE application.request_type SET display_group_name = 'General Registration' WHERE code = 'newApartment';
UPDATE application.request_type SET display_group_name = 'General Registration' WHERE code = 'removeRight';
UPDATE application.request_type SET display_group_name = 'Supporting' WHERE code = 'titleSearch';
UPDATE application.request_type SET display_group_name = 'Documents' WHERE code = 'cnclPowerOfAttorney';
UPDATE application.request_type SET display_group_name = 'Lease' WHERE code = 'varyLease';
UPDATE application.request_type SET display_group_name = 'General Registration' WHERE code = 'removeRestriction';
UPDATE application.request_type SET display_group_name = 'Supporting' WHERE code = 'cadastreBulk';
UPDATE application.request_type SET display_group_name = 'General Registration' WHERE code = 'newDigitalProperty';
UPDATE application.request_type SET display_group_name = 'Ownership' WHERE code = 'recordTransfer';
UPDATE application.request_type SET display_group_name = 'Systematic Registration' WHERE code = 'mapExistingParcel';
UPDATE application.request_type SET display_group_name = 'Systematic Registration' WHERE code = 'systematicRegn';

INSERT INTO system.version SELECT '1406b' WHERE NOT EXISTS (SELECT version_num FROM system.version WHERE version_num = '1406b');

